### ISSUE TITLE
Cloudwatch Logs

### ISSUE THREAD

**Issue by thomask** [iotFab/iota-aws-full-node#1]
Would be nice to add Cloudwatch Logs to this. Will create a PR if I can find the time in the coming days.

**Comment by thomask** [comment]
Not sure, would have to test to see what logging is available. The point would primarily be to get some transparency into what is going on. I launched the stack and know that it has been succesfully launched. However, I can't verify if everything is running correctly without SSHing into the instance, which might be too big a stretch for some.

**Comment by iotFab** [comment]
Cloudwatch will add extra cost but this could be set as an option.

If you did the KeyPair setup.
You can do ssh port redirection
`ssh -i "<your keypair>" -p 22 -L 9999:localhost:9999 ubuntu@<your host>`
 you have access to iota-pm on http://127.0.0.1:9999 on your computer's browser

**Actions** 
1) Document the port redirection
2) In todo add cloudwatch as an option

Are you good with that ?

**Comment by iotFab** [comment]
Updated CF template. 

if you enter your keypair  you will have commands to run to monitor EC2 from your PC
#2
