### ISSUE TITLE
Issue with Signature Requests

### ISSUE THREAD

**Issue by Akumar96** [iotFab/iota-aws-full-node#16]
The current error is coming:

"SignatureDoesNotMatchThe request signature we calculated does not match the signature you provided. Check your key and signing method.AKIAI5HZ6UQ52CI4LR4AAWS4-HMAC-SHA256 20180123T203739Z 20180123/us-east-2/s3/aws4_reques" 

Any insights to fixing this? 

Best Regard,
Akshay Kumar

**Comment by iotFab** [comment]
Where do you see this error message ? 

I cannot reproduce the error. 
I just updated to the new IRI version, please retry.
