### ISSUE TITLE
Issue with "WaitForInstanceWaitHandle"

### ISSUE THREAD

**Issue by Akumar96** [iotFab/iota-aws-full-node#17]
I've set it up multiple times but after creating "WaitForInstanceWaitHandle", it fails to create "WaitForInstance"  and eventually the whole thing doesn't create

**Comment by ryangadz** [comment]
i've had the same problem the last couple days which is weird because i had nodes running before. My node fell out of sync so i tried deleting it and starting over but now it fails to create an instance on aws.

**Comment by Akumar96** [comment]
Any updates? I think I figured it out. We need to use AWS T2.medium!

**Comment by iotFab** [comment]
Hi, 
t2.medium are the instances by default. 
What other instance type have you tried?

I cannot reproduce the error. 
I just updated to the new IRI version, please retry.

**Comment by ryangadz** [comment]
its working for me now. setup was very quick and node synced quickly
