### ISSUE TITLE
Invalid API Version

### ISSUE THREAD

**Issue by mirojo** [iotFab/iota-aws-full-node#18]
Hello,

I has used the Cloudformation to create the stack, but when i try to enter in the IRI URL in port 14265 always return this error:
{"error":"Invalid API Version","duration":0}

Please, help and thanks.

**Comment by mirojo** [comment]
When I execute "systemctl status iotapm" it returns this error:

Feb 02 15:05:07 XXX iota-pm[5473]:     at Object.invalidResponse (/usr/lib/node_modules/iota-pm/node_modules/iota.lib.js/lib/errors/requestErrors.js:5:12)
Feb 02 15:05:07 XXX iota-pm[5473]:     at makeRequest.prepareResult (/usr/lib/node_modules/iota-pm/node_modules/iota.lib.js/lib/utils/makeRequest.js:285:24)
Feb 02 15:05:07 XXX iota-pm[5473]:     at exports.XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/iota-pm/node_modules/iota.lib.js/lib/utils
Feb 02 15:05:07 XXX iota-pm[5473]:     at exports.XMLHttpRequest.dispatchEvent (/usr/lib/node_modules/iota-pm/node_modules/xmlhttprequest/lib/XMLHttpRequest.
Feb 02 15:05:07 XXX iota-pm[5473]:     at setState (/usr/lib/node_modules/iota-pm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
Feb 02 15:05:07 XXX iota-pm[5473]:     at exports.XMLHttpRequest.handleError (/usr/lib/node_modules/iota-pm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js
Feb 02 15:05:07 XXX iota-pm[5473]:     at ClientRequest.errorHandler (/usr/lib/node_modules/iota-pm/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:459:14)
Feb 02 15:05:07 XXX iota-pm[5473]:     at emitOne (events.js:116:13)
Feb 02 15:05:07 XXX iota-pm[5473]:     at ClientRequest.emit (events.js:211:7)
Feb 02 15:05:07 XXX iota-pm[5473]:     at Socket.socketErrorListener (_http_client.js:387:9)

**Comment by iotFab** [comment]
Have you updated your Wallet ?

**Comment by mirojo** [comment]
Ok, i have fixed this problem.
Now i'm trying to find the RocksDB PATH but i can't find it. Where is it?
No services running, no path, no installed packages.... RocksDB is missing but i read that IRI needs it.
Thanks for all!

**Comment by iotFab** [comment]
/home/iota/node/mainnetdb is the only DB I am aware of. 
Seems that RockDB can be embedded into the application through library (if I am right)
