### ISSUE TITLE
Specify required IAM permissions

### ISSUE THREAD

**Issue by wjmelements** [iotFab/iota-aws-full-node#20]
This is a feature request for the README to include the required IAM permissions.

**Comment by iotFab** [comment]
You mean the IAM permission to deploy the CF or the IAM permission deployed by the stack?

**Comment by wjmelements** [comment]
I believe the CF. At some point during setup it asked me to create a new permissions group.

**Comment by iotFab** [comment]
Sorry for the wrong label. 
I will try on a fresh account and keep you updated
