### ISSUE TITLE
AWS Template Access Denied

### ISSUE THREAD

**Issue by mario589736** [iotFab/iota-aws-full-node#6]
I am getting the following error when i try to set up the machine via the provided cloud formation template:

Template validation error: S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

Any ideas what that could be?

**Comment by iotFab** [comment]
Thank you for reporting this. 
This problem is on my side.
In waiting for the Fix, You can achieve the same by downloading the cloudformation.yml and providing it to AWS Cloudformation console.

**Comment by iotFab** [comment]
Launch stack button operational again
