### ISSUE TITLE
Connect to IOTA wallet

### ISSUE THREAD

**Issue by abel30567** [iotFab/iota-aws-full-node#8]
I got the node to run successfully but I can't seem to connect it to my IOTA wallet. Is there a way to connect these? I am running my IOTA wallet on my Mac can there be some clarification on this part?

**Comment by iotFab** [comment]
Yes, you can connect from your wallet using the following custom node: 
`http://<your ec2 hostname>:14265`
e.g.: http://ec2-256-257-258-259.eu-west-1.compute.amazonaws.com:14256
I will add extra documentation on this. 
If you start your node to share with other I would recommend the usage of Elastic IP to have a public, fixed ip dedicated to your host. 

Please note that your node need to be synced in order for you to connect to it.
